### ISSUE TITLE
execution problem

### ISSUE THREAD

**Issue by afpython** [mk-fg/python-libraptorq#5]
Hi mk-fg, I just cloned your libraptorq project into my pc. I already installed all needed dependencies but when i try to exec ./rq --debug encode -s16 -m200 --repair-symbols-rate 0.5 --drop-rate 0.3 setup.py setup.py.enc i get into this error message:

Traceback (most recent call last):
  File "./rq", line 237, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./rq", line 221, in main
    try: data = encode(opts, data)
  File "./rq", line 60, in encode
    opts.subsymbol_size, opts.symbol_size, opts.max_memory ) as enc:
  File "/usr/local/lib/python2.7/dist-packages/libraptorq/__init__.py", line 189, in __init__
    self._ctx_init = self._lib.RaptorQ_Enc,\
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 882, in __getattr__
    make_accessor(name)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 878, in make_accessor
    accessors[name](name)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 808, in accessor_function
    value = backendlib.load_function(BType, name)
AttributeError: function/symbol 'RaptorQ_Enc' not found in library '<None>': python2: undefined symbol: RaptorQ_Enc

So could you help me please to fix this issue, thanks in advance.

**Comment by mk-fg** [comment]
Hey,

Probably same issue as here - https://github.com/mk-fg/python-libraptorq/issues/3 - using unstable (latest) libRaptorQ v1.x, which has new API, which is not supported here.
Same solution - install lib version 0.1.9 or such.

Should probably add a note on that to the README too...
